Update agent_emcunity
Getting below error, 

  File "/omd/sites/canada/local/share/check_mk/checks/agent_emcunity", line 9, in agent_emcunity_arguments
    args += " -u " + quote_shell_string(params["username"])
KeyError: 'username'


So in file check_mk_emcunity/emcunity300/checks/agent_emcunity
Below changes required.

OLD :
 args += " -u " + quote_shell_string(params["username"])

New:
 args += " -u " + quote_shell_string(params["user"])